version: "3"

includes:
    rust:
        taskfile: ./sdk/rust/Taskfile.yml
        dir: ./sdk/rust

    swift:
        taskfile: ./sdk/swift/Taskfile.yml
        dir: ./sdk/swift

    java:
        taskfile: ./sdk/java/Taskfile.yml
        dir: ./sdk/java

    kotlin:
        taskfile: ./sdk/kotlin/Taskfile.yml
        dir: ./sdk/kotlin

    dart:
        taskfile: ./sdk/dart/Taskfile.yml
        dir: ./sdk/dart

tasks:
    build:
        deps:
            - rust:build
            - swift:build
            - kotlin:build

    format:
        deps:
            - rust:format
            - swift:format

    lint:
        cmds:
            - task: rust:lint
            - task: swift:lint

    package:
        deps:
            - rust:package
            - swift:package

    # TODO: publish
