version: "3"

includes:
    ":rust":
        taskfile: ../rust/Taskfile.yml
        dir: ../rust

tasks:
    build:
        deps: [":rust:build"]
        cmds:
            - dart analyze

    format:
        cmds:
            - dart format --fix .
