version: "3"

includes:
    ":rust":
        taskfile: ../rust/Taskfile.yml
        dir: ../rust

tasks:
    prepare:
        sources:
            - pubspec.yaml
        cmds:
            - dart pub get

    build:
        deps: [":rust:build", "prepare"]
        cmds:
            - dart run ffigen --config ffigen.yaml
            - dart analyze

    format:
        cmds:
            - dart format --fix .
