name: hedera_flutter
description: Native libraries for the Hedera™ Hashgraph SDK for Dart

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^1.1.2
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
