[workspace]
members = [".", "protobufs"]

[package]
description = "The SDK for interacting with Hedera Hashgraph."
edition = "2021"
license = "Apache-2.0"
name = "hedera"
readme = "../../README.md"
repository = "https://github.com/hashgraph/hedera-sdk-rust"
version = "0.1.0"

[lib]
bench = false
crate-type = ["lib", "staticlib", "cdylib"]

[features]
ffi = []

[dependencies]
async-stream = "0.3.3"
async-trait = "0.1.53"
backoff = "0.4.0"
base64 = "0.13.0"
ed25519-dalek = { version = "1.0.1", features = ["rand", "serde"] }
either = { version = "1.7.0", features = ["serde"] }
fraction = { version = "0.11.0", features = ["with-serde-support"] }
futures-core = "0.3.21"
futures-util = "0.3.21"
hedera-proto = { path = "./protobufs", features = [
    "serde",
    "time_0_3",
    "fraction",
] }
hex = "0.4.3"
hmac = "0.12.1"
http = "0.2.7"
itertools = "0.10.3"
k256 = "0.11.0"
log = "0.4.17"
num-bigint = "0.4.3"
once_cell = "1.10.0"
parking_lot = "0.12.0"
paste = "1.0.7"
pbkdf2 = "0.11.0"
pkcs8 = "0.9.0"
prost = "0.11.0"
rand = "0.8.5"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.79"
serde_with = { version = "2.0.0", features = ["hex", "base64", "time_0_3"] }
sha2 = "0.10.2"
sha3 = "0.10.2"
thiserror = "1.0.31"
time = { version = "0.3.9", features = ["serde"] }
tokio = { version = "1.18.1", features = ["rt-multi-thread"] }
tonic = "0.8.0"

[dev-dependencies]
anyhow = "1.0.57"
assert_matches = "1.5.0"
clap = { version = "3.1.18", features = ["derive", "env"] }
dotenv = "0.15.0"
expect-test = "1.4.0"
futures = "0.3"
hex-literal = "0.3.4"
pretty_env_logger = "0.4.0"
tokio = { version = "1.18.1", features = ["full"] }

[build-dependencies]
anyhow = "1.0.57"
cbindgen = "0.24.3"

[profile.release]
codegen-units = 1
debug = 0
lto = "fat"
opt-level = "z"
overflow-checks = false
panic = "abort"
strip = true

[patch.crates-io]
curve25519-dalek = { git = "https://github.com/launchbadge/curve25519-dalek", branch = "lb-update" }
ed25519-dalek = { git = "https://github.com/launchbadge/ed25519-dalek", branch = "lb-update" }
