[package]
name = "hedera"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
time = { version = "0.3.9", features = ["serde"] }
tokio = { version = "1.18.1" }
hedera-proto = { path = "../../protobufs/rust" }
serde_json = "1.0.79"
serde_with = "1.12.1"
tonic = { version = "0.7.1", features = ["compression"] }
async-trait = "0.1.53"
prost = "0.10.1"
hex = "0.4.3"
paste = "1.0.7"

[dev-dependencies]
anyhow = "1.0.57"
tokio = { version = "1.18.1", features = ["full"] }
