[package]
name = "hedera"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "staticlib", "cdylib"]
bench = false

[features]
ffi = []

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
thiserror = "1.0.31"
time = { version = "0.3.9", features = ["serde"] }
tokio = { version = "1.18.1" }
hedera-proto = { path = "../../protobufs/rust", features = ["time_0_3"] }
serde_json = "1.0.79"
serde_with = "1.12.1"
tonic = { version = "0.7.1", features = ["compression"] }
async-trait = "0.1.53"
prost = "0.10.1"
hex = "0.4.3"
paste = "1.0.7"
parking_lot = "0.12.0"
http = "0.2.7"
rand = "0.8.5"
log = "0.4.17"
backoff = "0.4.0"
ed25519-dalek = { version = "1.0.1", features = ["rand", "serde"] }
sha2 = "0.10.2"
itertools = "0.10.3"
once_cell = "1.10.0"
futures-util = "0.3.21"

[dev-dependencies]
anyhow = "1.0.57"
pretty_env_logger = "0.4.0"
tokio = { version = "1.18.1", features = ["full"] }

[build-dependencies]
anyhow = "1.0.57"
cbindgen = "0.23.0"
