version: "3"

silent: true

tasks:
    build:
        run: once
        sources:
            - src/**/*.rs
            - Cargo.lock
            - Cargo.toml
        cmds:
            # Build the Hedera Rust SDK (in debug mode)
            - cmd: cargo build --message-format=short

    format:
        cmds:
            - cargo fmt

    lint:
        cmds:
            - cargo clippy --message-format=short

    test:
        cmds:
            - cargo test

    example:
        deps: ["build"]
        cmds:
            - cargo run --example {{.CLI_ARGS}}
